### ISSUE TITLE
"Component named Apparatus could not be found"

### ISSUE THREAD

**Issue by joshuahhh** [idyll-lang/idyll-apparatus-component#1]
I installed this with `npm install --save idyll-apparatus-component` and put an `[Apparatus /]` component in my source file.

When I ran `npm start`, I got the message `Error: Component named Apparatus could not be found.` Given the [instructions for NPM components](https://idyll-lang.org/components-npm) in the Idyll docs, this surprised me.

I'll poke at it some more, though. Thanks!

**Comment by joshuahhh** [comment]
OK, egg on my face, `[IdyllApparatusComponent /]` worked! I had presumed there was some kind of webpack-like naming convention for components. (Is there some way to alias these things? Some kind of `require`-like helper?)

**Comment by mathisonian** [comment]
Apologies for the delayed response to all of this - I've been offline over the holidays and finally catching up. You can alias components in your `package.json` by adding an `idyll.components` entry:

```
"idyll": {
  "components": {
    "Apparatus": "node_modules/idyll-apparatus-component"
  }
}
``` 

I'm considering if we should add some sort of registration procedure where the components themselves can specify a shorthand name
